### ISSUE TITLE
Missing Methods! bluetoothle.initializePeripheral and other peripheral method not implemented.

### ISSUE THREAD

**Issue by blazekyo** [dodoinblue/ionic-native-bluetoothle#2]
following the documentation at: https://www.npmjs.com/package/cordova-plugin-bluetoothle#initializeperipheral

there should be method named 'initializePeripheral' but not found in the ionic-native wrapper.

**Comment by blazekyo** [comment]
I am willing to help in adding in the missing methods, but I am not a cordova devoloper and is stucked at understanding this part of code in the ionic-native-bluetoothle/BluetoothLe.js

    __decorate([
        Cordova({ successIndex: 0, errorIndex: 2, observable: true }),
        __metadata("design:type", Function),
        __metadata("design:paramtypes", [Object]),
        __metadata("design:returntype", Observable)
    ], BluetoothLe.prototype, "initialize", null);

    __decorate([
        Cordova({ callbackOrder: 'reverse', sync: true }),
        __metadata("design:type", Function),
        __metadata("design:paramtypes", []),
        __metadata("design:returntype", void 0)
    ], BluetoothLe.prototype, "enable", null);

**Comment by dodoinblue** [comment]
This repo needs a major updates since both its underlying projects `ionic-native` and `bluetoothle` have changed a lot. The official ionic-native documentations that describing these decorators are gone.
So I'm not sure you want to work on top of this project anymore.

**Comment by blazekyo** [comment]
if this is the only library left i could work on bringing bluetooth peripheral live to ionic capacitor, then I guess yeah 😅

may I know when should i use Observable, when should I use promise, or void as return type? 
also when should turn the sync flag to true?

**Comment by dodoinblue** [comment]
does this work for you? https://danielsogl.gitbook.io/awesome-cordova-plugins/bluetooth-le

If the api response is a one-time response, then use promise. i.e. reading from a characteristic. if you want to send updates whenever data changes, use Observable. i.e. subscribe to a characteristic.

**Comment by dodoinblue** [comment]
or this one? https://github.com/capacitor-community/bluetooth-le

**Comment by blazekyo** [comment]
I've found an alternative library for ionic-native port for cordova-bluetoothle
@ionic-native/bluetooth-le 
link: https://www.npmjs.com/package/@ionic-native/bluetooth-le
